### ISSUE TITLE
Unable to restore a BBR-deployment backup to a different target

### ISSUE THREAD

**Issue by brunograz** [shieldproject/shield#452]
Hi,

I'm currently testing a scenario where I have two installations of the same service - A and B both deployed with BOSH. 
I'm currently able to backup and restore the service when the target is the same in Shield - i.e. A -> A and B -> B - but whenever I try to restore the backup from A to B Shield throws an error. See below.

```
Running restore task (using bzip2 compression)
==============================================
bbr plugin starting up...
panic: runtime error: index out of range

goroutine 1 [running]:
main.BbrPlugin.Restore(0x633a41, 0x1a, 0x6305bc, 0xd, 0x62ed9f, 0x5, 0x62ead3, 0x3, 0x62e9b0, 0x2, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/bbr-deployment/plugin.go:282 +0x79f
main.(*BbrPlugin).Restore(0xc4200c2000, 0xc42006baa0, 0xc42006baa0, 0x0)
	:1 +0x81
github.com/starkandwayne/shield/plugin.dispatch(0x95c320, 0xc4200c2000, 0x5d11e2, 0x7, 0x0, 0xc420022580, 0x566, 0x0, 0x0, 0x0, ...)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/plugin.go:321 +0x9a2
github.com/starkandwayne/shield/plugin.Run(0x95c320, 0xc4200c2000)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/plugin.go:275 +0xf1e
main.main()
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/plugin/bbr-deployment/plugin.go:98 +0x174

EXITING 2
```

Both systems are backed up using the bbr-deployment plugin and have its own target in Shield.

Shield version - 8.0.15
BBR plugin version - 1.2.4 (bosh release v0.1.2)
Command executed to restore the archive - `shield restore-archive --target <target-B> <archive-uuid-from-A>`

**Comment by jhunt** [comment]
The crash is caused by this code:

```
backups, err := filepath.Glob(path.Join(tmpdir, joined))
if err != nil {
    return err
}
// execut bbr cli
cmd := exec.Command(fmt.Sprintf("%s/bbr", bbr.Bin),
  "deployment", 
  "--target", 
  bbr.Target,
  "--username",
  bbr.Username,
  "--password",
  bbr.Password,
  "--deployment",
  bbr.Deployment,
  "--ca-cert",
  caCertPath,
  "restore",
  "--artifact-path",
  backups[0],               /* nil dereference!!! */
)

plugin.DEBUG("Executing: `%s`", cmd)
```

(some liberties taken with formatting)

An immediate fix is to test that backups list is at least (exactly?) one element long.

The big question is why the glob doesn't resolve to a list of at least one path name.  What is your target configuration (please redact sensitive stuff)?

**Comment by jhunt** [comment]
Ah, in that case, I believe the problem is that the `bbr_deployment` name is used inside the zipped artifact, because of the way BBR works.  So the ZIP file has files under `concourse/*`, but the adusted target is looking for `concourse-test/*`

I believe the answer is: you cannot switch targets without keeping the deployment names the same.

@ramonskie may be able to weigh in with more details, as he is the BBR expert.

**Comment by ramonskie** [comment]
to my knowledge restoring with a different deployment name is not supported by bbr.
you can request a feature in https://github.com/cloudfoundry-incubator/bosh-backup-and-restore
once they build it in. we can fix it in the bbr_plugin for shield as well

**Comment by brunograz** [comment]
Interestingly I was able to restore the backup using the bbr command line tool - the backup was also taken using the bbr command line (Shield artifact was not used).

Here are the commands I executed:
```
./bbr deployment -t <REDACTED> --username <REDACTED> --deployment concourse --ca-cert <PATH_TO_CA> pre-backup-check
./bbr deployment -t <REDACTED> --username <REDACTED> --deployment concourse --ca-cert <PATH_TO_CA> backup
./bbr deployment -t <REDACTED> --username <REDACTED> --deployment concourse-test --ca-cert <PATH_TO_CA> restore --artifact-path concourse_20180913T152345Z/
```

**Comment by ramonskie** [comment]
@jhunt do we want to support the ability to change target. when restoring?
i don't see that this is currently possible for other plugins as well..

**Comment by jhunt** [comment]
It's possible, to an extent.  For example, `fs` plugins are tarballs made from the directory in question, so they can be replayed to other hosts, or even the same host in a different part of the filesystem.  That being said, the relational database plugins (`postgres`, `mysql`, and friends) often encode the database name in the backup archive contents, so while you can change the host, you cannot (for example) backup `database1` and restore it as `database2`.

What's the cost/benefit ratio?  How trivial is it to support?  How common is the scenario of restoring _elsewhere_?

**Comment by jhunt** [comment]
Having just re-plumbed the BBR plugins for 8.1, I can verify that this is doable, as long we are willing to accept all artifacts in the tarball (there _should_ only be one anyway).

I'll try to get that into the 8.1 changeset, for next week.

**Comment by jhunt** [comment]
I went to implement this this morning, and found that we may have already done that during the rewrite / re-splits work of 6453a09.

I will try to get a lab up today to verify that.
