### ISSUE TITLE
Shield web ui reports agent status as failing but it works (backup and restore)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [shieldproject/shield#496]
Hello,

Shield web ui reports agent status as failing whereas the agent works as expected (it performs backup and restore).
The message is the following : 
Note:
This SHIELD agent is not reporting its version, which means that it is probably a v6.x version of SHIELD.  It will not be able to report back health and status information to this SHIELD Core.  Similarly, plugin metadata will be unavailable for this agent, and SHIELD operators and site administrators will have to operate without it for all targets that use this agent for backup and restore operations.

The shield core is configured with a dynamic ip allocated by bosh.
The release cf-routing (with the job route_registrar) is used in order to open a route (name) on this dynamic ip.
The domain property in the core job is valuated with the name.  

Thanks and regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello James,

Sorry again for my late answer.
What do you mean by "Does the IP address in the Agents part of the admin UI match your expectations, knowing your internal network topology ?"
Regards,
Jean-Christophe.

**Comment by jhunt** [comment]
If you look at the "Agents of SHIELD" screen, accessible from the Admin page in the web UI (when logged in as a site admin), there will be a IP address listed for the registered agent.  Does that IP address correspond to the IP of the host where the agent is running, or is it the IP address of something else?

**Comment by jhunt** [comment]
Reopening with new information from #635

**Comment by jhunt** [comment]
Based on the information presented in #635, it appears that this agent was previously registered under a different IP address.  Can you verify, @JCL38-ORANGE ?

**Comment by JCL38-ORANGE** [comment]
Hello,

I will take time to give you information about that.
Sorry for the delay.
Regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Hello,

In fact it was a different bosh deployment.
In the Web UI/Agents of SHIELD, I see : 

bosh-master/bosh@z1/0 | **192.168.116.158**, **192.168.99.82:5444** |   | error | 2s ago | 20m ago | yes | hide                       \| resync
-- | -- | -- | -- | -- | -- | -- | --
ERROR:The SHIELD Core was unable to check the status of this agent (see task 55c210f6-5e09-471a-bd09-43010d516e02)                                                               Note:This SHIELD agent is not reporting its version, which means that it is probably a v6.x version of SHIELD.  It will not be able to report back health and status information to this SHIELD Core.  Similarly, plugin metadata will be unavailable for this agent, and SHIELD operators and site administrators will have to operate without it for all targets that use this agent for backup and restore operations.
192.168.116.158 is the IP address of a bosh director that we want to backup with shield 8.5.0.
192.168.99.82 is the IP address of the go router in front of shield core.
The agent refers to shield core through the Go Router (routing-release) and the spec field shield-url.
Is there a workaround for that ?
The display was not clean in 8.4.0 but the WebUI gives information.
Now with 8.5.0, I have the message "Uh-oh — Something broke" when I want to display my data system.
Sorry again for my late answer
Regards,
Jean-Christophe.
