### ISSUE TITLE
Plugin S3 fails with storage configured with auth v2

### ISSUE THREAD

**Issue by JCL38-ORANGE** [shieldproject/shield#499]
Hello,

I re-open this issue.
I am targeting the following S3 storage +> https://www.orange-business.com/fr/produits/flexible-storage
When I target a S3 storage (auth v2) with the S3 plugin, the following error is raised :   
...
(InvalidDateFieldInRequest) [raw
InvalidDateFieldInRequest
]

EXITING 4
shield worker 1 unable to run command against 127.0.0.1:5444
...
Previously, we used the scality plugin with this S3 storage. It was working perfectly.
Currently, it works well with an another S3 storage (auth V4) like minio bosh release or AWS.
Is the problem related to https://github.com/starkandwayne/shield/issues/464 ?
Thanks in advance for your help.
Regards,
Jean-Christophe.

**Comment by zethis** [comment]
@JCL38-ORANGE on à patcher de notre coté le soucis S3, passe dans le bureau (Team OASIS/SHM)

**Comment by jhunt** [comment]
If I may ask, what was the nature of the patch to your S3 store, and does that mean we can close this issue?

**Comment by jhunt** [comment]
Closing this due to lack of response from originating team.  Feel free to reopen to continue the discussion.

**Comment by JCL38-ORANGE** [comment]
Hello James,

Sorry for my late answer.
I have just bumped shield 8.1.0.
Plugin S3 fails with storage configured with auth v2 even with shield 8.1.0.
The message is always : 
DEBUG> 'store' action returned error:  (InvalidDateFieldInRequest) [raw <?xml version="1.0" encoding="UTF-8"?>
DEBUG> <Error><Code>InvalidDateFieldInRequest</Code>
DEBUG> <Message></Message>
DEBUG> </Error>
DEBUG> ]
 (InvalidDateFieldInRequest) [raw <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidDateFieldInRequest</Code>
<Message></Message>
</Error>
]
 
Regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
@zethis Hello, Could you share your solution to shield team in order to include in the next release ? 
Regards,
Jean-Christophe.
