### ISSUE TITLE
[BUG] Issues with hiding shield agents

### ISSUE THREAD

**Issue by patjones** [shieldproject/shield#548]
**Describe the bug**
clicking `hide` on a  shield agent won't collapse anything and just spit you back at the admin page.

**To Reproduce**
1. Have a list of agents including an unresponsive agent.
2. hit `hide`

**Expected behavior**
The hide button should collapse the Note: to make the agent list more streamline

 - SHIELD Core: [e.g. 8.2.0]

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: [OSX]
 - Browser: [chrome]
 - Version: [Version 74.0.3729.131 (Official Build) (64-bit)]

**Comment by jhunt** [comment]
This stems from a confusing use of the term "hide".

Here is a "hidden" agent:

<img width="814" alt="Screen Shot 2019-08-22 at 11 27 03 AM" src="https://user-images.githubusercontent.com/20047/63527930-fdfcfa80-c4cf-11e9-9b12-006defb040ab.png">

Perhaps we should move hidden agents into a separate table down below the "active" agents, and put verbiage in to explain the different categorizations, and what "hide" actually does / means.

Putting this in v8.5

**Comment by jhunt** [comment]
Idea:

<img width="840" alt="Screen Shot 2019-08-23 at 8 30 28 AM" src="https://user-images.githubusercontent.com/20047/63592832-918e0400-c580-11e9-8b9b-be3b4d980ae7.png">
