### ISSUE TITLE
[NEW] Have a built in wizard option to backup shield

### ISSUE THREAD

**Issue by patjones** [shieldproject/shield#551]
SHIELD knows more about how to back itself up than I do. Have an option in the wizard to have automatically back up SHIELD data dir. SHIELD self backups are important and we should make it as easy as possible to create. Maybe it would make sense to run through backing up SHIELD as part of the SHIELD init process?

**Describe what you would like to see**
I would like in the new target wizard to quickly be able to backup shield itself.

**Describe alternatives you've considered**
Document and hope shield users create shield backups from these docs.

**Comment by jhunt** [comment]
Perhaps the easiest way to do this is to "shim in" a plugin type of `shield`, and have the API interpret that to mean "fs, with these options"
