### ISSUE TITLE
[BUG] agents of shield page loads forever

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#552]
**Describe the bug**

The agents of shield page loads, shows the list of agents for a moment, and then loads again but never returns to the list.

**To Reproduce**
1. Go to the admin tab
2. Go to the Agents of SHIELD page

**Expected behavior**

It should only load once

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.2.1

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: windows
 - Browser: firefox
 - Version: 67.0.1

**Additional context**

**Comment by jhunt** [comment]
I believe this has been fixed in 7c98b5b19, as I noticed the same behavior semi-independently while I was working on some other agent-related functionality.
