### ISSUE TITLE
[BUG] Redacted secrets are not hidden on the data system page's configuration section

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#554]
**Describe the bug**
Seen in the Postgres plugin.

The password is being shown in plaintext on the data system page.

**To Reproduce**
1. Make a data system using the postgres plugin
2. Go to the data system's page
3. Look at the configuration section
4. Read the password with your eyes

**Expected behavior**
I should not have been able to read the password with my eyes without doing something to unhide it first

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.2.1

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Windows
 - Browser: Firefox
 - Version: 67.0.1

**Additional context**

**Comment by thomasmitchell** [comment]
I could show a picture of the password not being redacted, but then I'd have to redact it to put it on Github

**Comment by thomasmitchell** [comment]
Of note, the password was redacted while entering it into the wizard.

**Comment by jhunt** [comment]
Confirmed on latest master commit.  Putting this in v8.5 milestone

**Comment by jhunt** [comment]
BAM!

<img width="401" alt="Screen Shot 2019-09-05 at 10 02 14 PM" src="https://user-images.githubusercontent.com/20047/64395743-47e5f480-d029-11e9-9360-67487b3f6fe3.png">
