### ISSUE TITLE
[BUG] SHIELD Agent Can't Trust System Cert Pool

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#556]
**Describe the bug**
You can't not specify the core cert and let the agent trust the system cert pool

**To Reproduce**
1. Have the core be signed by a system-trusted CA
2. Try to configure the shield agent with no specific CA cert
3. Registration should complain that the remote certificate is signed by an untrusted source.

**Expected behavior**
It should have trusted the system cert pool

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.2.1

**Additional context**

**Comment by jhunt** [comment]
This is something we should put into testdev.

**Comment by jhunt** [comment]
Turns out that this is next to impossible to put into testdev reliably; we'll have to find something (i.e. Docker) that's more deterministic (re: system pool composition) for testing.
