### ISSUE TITLE
[BUG] Archive not present until refresh

### ISSUE THREAD

**Issue by sriniketh923** [shieldproject/shield#557]
**Describe the bug**
After a backup is configured, the data backed up is not reflected in the restore archives unless the page is refreshed. This happens when SHIELD is compiled locally using the Makefile.

**To Reproduce**
1. Compile SHIELD locally using "make shield dev"
2. Configure a backup
3. Click on Restore data from backup
4. Click on Choose a data system
5. Pick a data system
6. No archives show up even though files are backed up to WebDav
7. Go to the SHIELD home page
8. Go back to Restoring data and the archives show up

**Expected behavior**
The archives in the restore should be there without refreshing the page

**Screenshots**
Backup complete:
![Screen Shot 2019-06-20 at 3 13 55 PM](https://user-images.githubusercontent.com/22748009/59875263-4d0e9e00-936e-11e9-8c0d-745d46e69bac.png)

No archives in restore:
![Screen Shot 2019-06-20 at 3 17 02 PM](https://user-images.githubusercontent.com/22748009/59875373-9eb72880-936e-11e9-88b8-c68f556892cd.png)

WebDav file:
![Screen Shot 2019-06-20 at 3 17 34 PM](https://user-images.githubusercontent.com/22748009/59875391-ac6cae00-936e-11e9-83f0-c65949d1a56d.png)

**SHIELD Version**
 - SHIELD CLI: v8.1.0

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: OSX
 - Browser: firefox
 - Version: 67.0.1 (64 bit)

**Comment by jhunt** [comment]
This is related to #550 (same root cause, different symptomatic fallout)

**Comment by jhunt** [comment]
I'm going to close this since the fix for #550 should take care of this one as well.
