### ISSUE TITLE
[BUG] testdev:failed to retrieve encryption parameters for [fixed_key]: not found in vault

### ISSUE THREAD

**Issue by nahmad-vf-ic-pk** [shieldproject/shield#558]
**Describe the bug**
SHEILD testdev fails to run a backup job. 

**To Reproduce**
1. Go to SHIELD's UI http://localhost:8181
2. Configure a new job. Choose "SHIELD" as Data System. Choose "CloudStor" as Cloud Storage.
3. Schedule a backup job. 
4. See error under Timeline. Click on "full task log"

**Expected behavior**
The job fails and outputs error as shown in the screenshot below. @jhunt suspects this is a `vault` error.

**Screenshots**

![Screen Shot 2019-06-26 at 1 52 49 PM](https://user-images.githubusercontent.com/23199404/60206688-352d9300-9822-11e9-813a-0d87c262cb09.png)

**SHIELD versions (please complete the following information):**
 - SHIELD Core: v8.2.1
 - SHIELD CLI: v8.1.0

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 74.0.3729.157 (Official Build) (64-bit)

**Additional context**

**Comment by jhunt** [comment]
IIRC, this ended up being related to Vault 1.1.x, which SHIELD doesn't currently support.
