### ISSUE TITLE
[NEW] MongoDB flags passed separately for mognodump and mongorestore

### ISSUE THREAD

**Issue by xMordax** [shieldproject/shield#570]
**Is your feature request related to a problem? Please describe.**
The MongoDB parameters/flags for ```mongodump``` and ```mongorestore``` are the same instead of them being passed separately, probably because the function just collects the flags and then passes it to the Exec function(https://github.com/shieldproject/shield/blob/master/plugin/mongo/plugin.go#L231).
Which for example created the problem that we cannot pass the ```--drop``` flag at the ```mongorestore``` since ```mongodump``` does not recognize it(which is good, in a way ;)).

Probably it is the same problem as explained here: https://github.com/shieldproject/shield/issues/478

**Describe the solution you'd like**
It would be nice to have two saprate flag fields that you can configure, one for ```mongodump``` and one for ```mongorestore```
https://github.com/shieldproject/shield/blob/master/plugin/mongo/plugin.go#L91-L97

**Comment by jhunt** [comment]
This definitely looks doable, especially if the proposed solution is to just split `mongo_options` into two different flags, `mongorestore_options` and `mongodump_options`.  We could even keep the legacy `mongo_options` as a shared flag set, we have backwards compatibility!

Are you interested in submitting a PR to move past deficiency?
