### ISSUE TITLE
INNER JOINs are not happy with Thing Deletion

### ISSUE THREAD

**Issue by jhunt** [shieldproject/shield#581]
Vet the use of INNER JOINs and `db.Get*()` functions that don't check for non-error nil-results (i.e. "not here, mate") and fix up accordingly.

We probably need a battery of tests to catch these, in unit testing.

**Comment by jhunt** [comment]
Vetted!

**Comment by jhunt** [comment]
only kidding.  Found some more.

**Comment by thomasmitchell** [comment]
The current state of this is keeping archives associated with deleted targets from being purged.

**Comment by jhunt** [comment]
We should definitely write some t/api tests to exercise deletion better.
