### ISSUE TITLE
[NEW] Purge old task logs

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#589]
**Is your feature request related to a problem? Please describe.**
Task logs are kept around in the database forever. This means that the database will embiggen boundlessly. 

**Describe the solution you'd like**
Purge task logs older than some duration.

**Describe alternatives you've considered**

**Comment by jhunt** [comment]
Fun Fact: `boundless-embiggening` was the name of the first Kubernetes deployment of SHIELD's forthcoming Helm chart!

**Comment by jhunt** [comment]
Proposal:

Create new configuration options for setting the "historical" retention of metadata.  Apply this to Tasks and purged Archives, according to the following rules:

1. No purged archives should be kept for longer than X days
2. Orphaned tasks should never be kept
3. No "system" tasks (test-store, agent-status, etc.) should be kept for longer than Y days

The new configuration option supplies the values of X and Y:

```
# ... the rest of shieldd.yml ...
metadata:
  retention:
    purged_archives: 7d
    system_tasks:    14d
```

**Comment by jhunt** [comment]
Opted to retain all task _entries_, but just remove the task log content, replacing it with `(log truncated)` string.  New configuration for shieldd.yml looks like this:

```
metadata:
  retention:
    purged_archives: 90d
    task_logs:       45d
```
