### ISSUE TITLE
[NEW] Web UI should update available agents for backup jobs when new agents register

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#597]
**Is your feature request related to a problem? Please describe.**
I could not find the new agent in the list of agents when configuring a new target because I had not refreshed the page since then.

**Describe the solution you'd like**
Update this via websocket.

**Describe alternatives you've considered**
Refreshing the page is an easy workaround, but it can be unintuitive as most things in the web ui update without a refresh.

**Comment by jhunt** [comment]
Agent is not yet support in the message bus, but this seems doable.  With ActiveFabric (#545) and Tenant Scoped Agents (#543) we should even be able to target the mbus updates to specific queues.
