### ISSUE TITLE
[BUG] schema v10 cleanup doesn't work when duplicate agents have same last_seen_at

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#601]
**Describe the bug**
So it fails when you try to upgrade for the very thing the migration is attempting to fix. This is exacerbated by the fact that SHIELD updates all of the last_seen_ats for the duplicates when one check is done successfully.

**To Reproduce**
1. make duplicate agents in the db with the same last_seen_at schema v9
2. set the schema version to 9
3. try to run the migration
4. See shieldd fail to start

**Expected behavior**
I expected it to successfully do the cleanup

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.4.1
 - SHIELD CLI: n/a

**Browser version(s) (please complete if reporting a web UI bug):**
n/a

**Additional context**

**Comment by thomasmitchell** [comment]
```
delete from agents
where uuid != 
  (select uuid from agents a2 
  where agents.address = a2.address and a2.last_seen_at = 
    (select MAX(last_seen_at) from agents a3 
    where a2.address = a3.address) 
  order by uuid asc
  limit 1);
```

**Comment by jhunt** [comment]
```
delete from brain
  where sql_query = $that_one_up_there
```

😝
