### ISSUE TITLE
[NEW] shield status should report core lock status

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#606]
**Is your feature request related to a problem? Please describe.**
Just want to know if the core is locked from the CLI

**Describe the solution you'd like**
`shield status` is already a command. Let's have it report the lock status.

**Describe alternatives you've considered**
`shield curl`? Just logging into the web UI?

**Comment by jhunt** [comment]
How's this?

<img width="355" alt="Screen Shot 2019-09-06 at 3 00 35 AM" src="https://user-images.githubusercontent.com/20047/64407525-83e17f80-d052-11e9-8cc8-c6aaf8901416.png">
