### ISSUE TITLE
[BUG] Cannot delete agents, missing column

### ISSUE THREAD

**Issue by jordanbcooper** [shieldproject/shield#608]
**Describe the bug**
Attempted to delete agents that are no longer reporting or should not be reporting to SHIELD CORE. Saw missing column in shield logs.

**To Reproduce**

Upgraded from 8.1 to 8.4.1
Attempted to delete agents via CLI, saw logs:

`2019-09-09 18:49:04.107692277 +000 UTC /var/vcap/packages/shield/bin/shieldd: ERROR: DELETE /v2/agents/b3e3c4a3-19e1-44f1-b2f6-a4537599c109 errored: unable to determine if agent can be deleted: no such column: agent`

**Expected behavior**
I should be able to delete agents that are no longer reporting or should not be reporting to SHIELD CORE

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.4.1
 - SHIELD CLI: 8.4.1

**Additional context**
Also unable to load "Agents of Shield" on admin page, possible related? Something seems to be missing from the DB. I also do not see any tables with the column "agent", but I do see an "agents" table.

**Comment by jordanbcooper** [comment]
Update-- after upgrade it seemed the agents were just taking time to be "checked". I can see the agents of shield admin page. Available agents show up in CLI, but I cannot delete errored agents.

**Comment by jordanbcooper** [comment]
I read the code-- https://github.com/shieldproject/shield/blob/b59b608b3ed74613c8331bc047e88be26947fbd4/db/agents.go#L251-L263

Looks like this is trying to find `agent` in the jobs table, but then tries to drop something from the `agents` table.

**Comment by jhunt** [comment]
That's a self-protective measure to make sure we don't delete an agent that is still in use.

First we ask _are there any jobs for which the agent to be deleted is the agent of the job?_ (`SELECT something FROM jobs WHERE agent = $address`)

If we find any, it's a problem and we bail out early.

If there are no jobs associated with the agent, then we can delete the agent, from the agents table.

The only problem is: jobs don't have agents; targets do.  (Also, stores do, but that's a different issue).

**Comment by jordanbcooper** [comment]
I figured as much, thanks James. Did I skim poorly or is there not a schema that adds `agent` to the jobs table?
