### ISSUE TITLE
[NEW] Update Web UI when tenant membership or role changes

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#610]
**Is your feature request related to a problem? Please describe.**
Updating your tenant membership requires a refresh to be visible

**Describe the solution you'd like**
Update the web UI top right dropdown (and probably Tenants list on the admin page) when membership or role changes. This is dependent on #609 

**Describe alternatives you've considered**
Polling.

**Comment by thomasmitchell** [comment]
Also, if you're switching into a higher or lower role, the buttons available to you need to be updated.

**Comment by jhunt** [comment]
Fixed in #625!
