### ISSUE TITLE
[NEW] Prometheus Exporter

### ISSUE THREAD

**Issue by jhunt** [shieldproject/shield#615]
**Is your feature request related to a problem? Please describe.**
I want to be able to monitor SHIELD with minimal effort.

**Describe the solution you'd like**
Build a Prometheus exporter into the SHIELD API

**Comment by Scoobed** [comment]
Is it known what the changes that need to happen with the existing Prometheus Exporter for Shield

As we looking for this exact item, or is that something that will be fixed in 8.6 release

**Comment by jhunt** [comment]
This is in the 8.6 milestone, and we expect it to be completed for that.

**Comment by jhunt** [comment]
Here's the design document we are currently pursuing / formulating:

https://github.com/shieldproject/notebook/blob/master/proposals/prometheus.md

**Comment by Scoobed** [comment]
Is there a alerting component to the Shield Exporter and does it integrate the existing one in the Prometheus project

For example https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/shield_alerts/spec.  Are these going to be updated for 8.6 or starting over?

**Comment by jhunt** [comment]
If alerting is valuable to you, I'd love to hear what you need / want to alert on.  We can make the exporter do whatever Prometheus-type folks think is valuable.
