### ISSUE TITLE
[BUG] Web ui showing tenants that should no longer be preset after a restore.

### ISSUE THREAD

**Issue by patjones** [shieldproject/shield#623]
**Describe the bug**
If I restore a shield archive and expect a tenant to be missing from the restore it is still present

**To Reproduce**
1. Do a backup of shield itself
2. Create a tenant 
3. Restore shield
4. See that the tenant is still present even on different browsers and machines
5. check the DB on box and see that the tenant is not present

**Expected behavior**
I expect the tenant to be gone after I restored from a previous archive

**SHIELD versions (please complete the following information):**
 - SHIELD Core: [e.g. 8.5.0]

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: [e.g. OSX]
 - Browser: [e.g. firefox, chrome, safari]

**Comment by jhunt** [comment]
This has been fixed with the new metashield plugin available in 8.7.0.
