### ISSUE TITLE
[BUG]Uh-oh — Something broke - unable to retrieve target configuration: agent metadata not found in database.

### ISSUE THREAD

**Issue by JCL38-ORANGE** [shieldproject/shield#635]
**Describe the bug**
When I want to display my data system, I am facing with the message : 
Uh-oh — Something broke.

An unknown error has occurred.
In the log file, the message is : 
2019-10-02 10:27:41.898163472 +000 UTC /var/vcap/packages/shield/bin/shieldd: ERROR: GET /v2/tenants/ac639cbf-b0c6-4038-9e76-747a45d032dd/systems/c93c02c2-2c38-40bb-ba1d-c0ef909094a3/config errored: unable to retrieve target configuration: agent metadata not found in database.

**To Reproduce**
My specific context is described there : https://github.com/shieldproject/shield/issues/496#issuecomment-494176711
In the screen "Agents of SHIELD" , the report is : 

mongodb/shield@z1/0 | 192.168.211.22, 192.168.99.81:5444 |   | error | 36m ago | 30m ago | yes | hide                       \| resync
-- | -- | -- | -- | -- | -- | -- | --
ERROR:The SHIELD Core was unable to check the status of this agent (see task 51cb0724-3f8d-499f-a60e-bf955c0a1065)                                                               Note:This SHIELD agent is not reporting its version, which means that it is probably a v6.x version of SHIELD.  It will not be able to report back health and status information to this SHIELD Core.  Similarly, plugin metadata will be unavailable for this agent, and SHIELD operators and site administrators will have to operate without it for all targets that use this agent for backup and restore operations.

**Expected behavior**
The agent status was the same in the 8.4.0 release and it was possible to display my data system without problems. 

**SHIELD versions (please complete the following information):**
 - SHIELD Core: [e.g. 8.5.0] - Bosh release context

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: [windows]
 - Browser: [firefox]

**Additional context**
Closely related to this https://github.com/shieldproject/shield/issues/496#issuecomment-494176711

**Comment by jhunt** [comment]
Reopening #496, and closing this one.
