### ISSUE TITLE
[NEW] Users should be able to update their own password

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#642]
**Is your feature request related to a problem? Please describe.**
I would like to change my own password without having administrative privileges on the SHIELD

**Describe the solution you'd like**
There should be an API endpoint that requires your existing password and new password to change the password. There should also be a new CLI command and Web UI page for accessing this capability.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have
considered.

Be an admin and edit your account? Ask an admin to edit your account?

**Comment by jhunt** [comment]
This works, fwiw:

```
→  shield -c integration-tests login
SHIELD Username: admin
SHIELD Password:
logged in successfully

→  shield -c integration-tests create-user
Display Name: Foo
Username: foo
Choose a password:
Confirm password:
UUID:        9a622e75-9df6-43ef-8c06-6669c9ff4f9a
Name:        Foo
Account:     foo
System Role:

→  shield -c integration-tests login
SHIELD Username: foo
SHIELD Password:
logged in successfully

→  shield -c integration-tests passwd
Current pasword:
Pick a new password:
Confirm new password:
Password changed successfully
```
