### ISSUE TITLE
[BUG] Web UI plugin metadata may be inaccurate for selected plugin

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#660]
**Describe the bug**
When editing target/store configurations in the web ui, either through the wizard or through the edit configuration page, available properties for plugins may be inaccurate. This is regardless of the agent metadata contained in the SHIELD database, or even the data contained in AEGIS in the web UI.

**To Reproduce**
1. Have a SHIELD agent v8.0.15
2. Have a SHIELD agent v8.6.0
3. Make an fs target
4. Notice that for one of them, `strict` is either there or not there, the opposite of what it should be.

**Expected behavior**
I expected the metadata to reflect what the selected agent reports.

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.5.0
 - SHIELD CLI: n/a

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: OSX Mojave
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
This is most likely due to a bug in the `AEGIS.agent` function. We're shadowing the passed in parameter in the for loop, causing the function to always return the first agent in AEGIS, in whatever arbitrary order it is internally sorted in the hash.

**Comment by jhunt** [comment]
I believe this is fixed in #661
