### ISSUE TITLE
[BUG] metashield plugin should trust system pool if ca not specified

### ISSUE THREAD

**Issue by thomasmitchell** [shieldproject/shield#687]
**Describe the bug**
If CA certificate is not specified to the metashield plugin, then the SHIELD endpoint can never actually be trusted.

**To Reproduce**
1. Make a metashield backup against a shield server with a system pool trusted certificate
2. Don't skip ssl validation
3. Don't specify a ca certificate
4. watch the backup fail

**Expected behavior**
I expected the plugin to use the system certificate pool if no ca was given

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.7.2
 - SHIELD CLI: n/a

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: [e.g. OSX, windows]
 - Browser: [e.g. firefox, chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by sriniketh923** [comment]
Should be fixed now
